### PR TITLE
Add treasury pallet 

### PR DESCRIPTION
**Pull request by echevrier**
To be improved as issue https://github.com/integritee-network/integritee-node/issues/33 is not clear.
Config with no burn and impossibility to approve a proposal.

### CODE REVIEW

**Comment by brenzi** [comment]
if #33 is clear now, please update the description of the PR.
Would you now consider #33 done?
Then I'll run this node and test to review. The allocation math is a bit adventurous, but that's kind of out of scope of this task. It's just about having a treasury and fees being collected in it

**Comment by brenzi** [comment]
How did you check the treasury balance change? That the fee is paid to the treasury? I could verify that it isn't burned, which is a good sign. But js/apps doesn't give me all digits to verify the treasury balance.

I played with a python script but couldn't get treasury balance yet

**Comment by brenzi** [comment]
keep it simple: set initial treasury balance to zero and watch it rising when extrinsics are included. this can be done with js/apps manually. 

for an automated approach see: https://github.com/polkascan/py-substrate-interface/issues/130

**Comment by brenzi** [comment]
ok. treasury balance can't be below ED, which here is 1mTEER. But that's low enough to see that fees are sent to treasury. After one extrinsic, the treasury holds 1.2mTEER, what corresponds well enough with the fees paid: 271_000_000
decimals are: 12

**Review by brenzi — APPROVED** [review]
we will need to change the allocations and will need to burn all fees at the beginning, according to our burning mechanism.
But I approve as this first step behaves as expected

**Comment by brenzi** [comment]
treasury balance test script (will commit this to repo/scripts. maybe useful for CI):
```python
#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Thu Sep 16 20:41:13 2021

@author: brenzi
"""

from substrateinterface import SubstrateInterface, Keypair
from substrateinterface.utils.ss58 import ss58_encode

def get_balance(who):
    return substrate.query('System', 'Account', params=[who]).value['data']['free']

substrate = SubstrateInterface(
        url="ws://127.0.0.1:9944",
        type_registry_preset='kusama'
    )
alice = Keypair.create_from_uri('//Alice')
dave = Keypair.create_from_uri('//Dave')
treasury = ss58_encode('0x' + b'modlpy/trsry'.hex() + '0000000000000000000000000000000000000000')

alicebefore = get_balance(alice.ss58_address)
treasurybefore = get_balance(treasury)
totalissuancebefore = substrate.query('Balances', 'TotalIssuance')
print('total issuance', totalissuancebefore)

amount = 10 * 10**9 #milli

call = substrate.compose_call(
    call_module='Balances',
    call_function='transfer',
    call_params={
        'dest': dave.ss58_address,
        'value': amount
    }
)

payment_info = substrate.get_payment_info(call=call, keypair=alice)
print("Payment info: ", payment_info)

extrinsic = substrate.create_signed_extrinsic(
    call=call,
    keypair=alice,
    era={'period': 64}
)
receipt = substrate.submit_extrinsic(extrinsic, wait_for_inclusion=True)
print('extrinsic sent')

totalissuanceafter = substrate.query('Balances', 'TotalIssuance')
print('difference in total issuance: ', totalissuancebefore.value - totalissuanceafter.value)

aliceafter = get_balance(alice.ss58_address)

paidfee = alicebefore - aliceafter - amount
print('fee paid : ', paidfee)

treasuryafter = get_balance(treasury)

print('treasury balance is ', treasuryafter, ' and has increased by', treasuryafter-treasurybefore)
```

**Comment by echevrier** [comment]
> if #33 is clear now, please update the description of the PR.
> Would you now consider #33 done?
> Then I'll run this node and test to review. The allocation math is a bit adventurous, but that's kind of out of scope of this task. It's just about having a treasury and fees being collected in it

For #33 I assumed:
- the allocation math is : 5% of  Nbr of endowed_account * 1 << 60
- The treasury is configured so that:
1. Proposals can be done, but not accepted/refused, ... (MaxApprovals = 0)
2. SpendPeriod cannot be 0, so same value as in Polkadot: 24 days
3. ProposalBond, ... undefined, as we don't handle Proposals.
So we can close it, if you agree with these assumptions.

**Comment by echevrier** [comment]
> How did you check the treasury balance change? That the fee is paid to the treasury? I could verify that it isn't burned, which is a good sign. But js/apps doesn't give me all digits to verify the treasury balance.
> 
> I played with a python script but couldn't get treasury balance yet

I added in the worker client a command to request the treasury balance. I also add a script for CI. But I haven't push it, as we need to merge first the node, to make the worker compatible with this version

**Comment by echevrier** [comment]
> keep it simple: set initial treasury balance to zero and watch it rising when extrinsics are included. this can be done with js/apps manually.
> 
> for an automated approach see: [polkascan/py-substrate-interface#130](https://github.com/polkascan/py-substrate-interface/issues/130)

I don't understand it

**Pull request merged**
