### PR TITLE
Move verification logic from pallets to worker

### PR DESCRIPTION
**Pull request by gaudenzkessler**
* Increase transaction version and spec version

### CODE REVIEW

**Comment by haerdib** [comment]
This PR should also include the new pallet, I suppose?

**Comment by haerdib** [comment]
If there was a change in the pallet txs, there should also be a change in the weights, because a function has been removed. So it's a little strange that this builds and passes the CI. Do you know why?

**Comment by gaudenzkessler** [comment]
The weights have not been removed. I opened a new PR for that. 

https://github.com/integritee-network/pallets/pull/86

**Review by haerdib — APPROVED** [review]
LGTM :)

**Pull request merged**
